### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/nuScenes/samples/RADAR_FRONT/n015-2018-07-18-11-07-57+0800__RADAR_FRONT__1531883530440378.pcd'

### ISSUE THREAD

**Issue by KamiKamiKumo** [youngskkim/CRN#20]
In step4, when I run 'python scripts/gen_radar_bev.py', the error is reported as follows: 

Traceback (most recent call last):
  File "scripts/gen_radar_bev.py", line 165, in <module>
    worker(info)
  File "scripts/gen_radar_bev.py", line 84, in worker
    current_pc = RadarPointCloud.from_file(file_name, invalid_states, dynprop_states, ambig_states)
  File "/root/miniconda3/envs/CRN/lib/python3.8/site-packages/nuscenes/utils/data_classes.py", line 386, in from_file
    with open(file_name, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/nuScenes/samples/RADAR_FRONT/n015-2018-07-18-11-07-57+0800__RADAR_FRONT__1531883530440378.pcd'

Just like the picture: 
![A{(3LJB%MY}Q5LH_C2K YFE](https://github.com/youngskkim/CRN/assets/61053986/e57eb1d4-d7ce-4ed8-bd81-fdb72fd40f2d)
This is my folder directory:
![0Y3N0$6U}}E9RU2 0)53({K](https://github.com/youngskkim/CRN/assets/61053986/2333731f-daf3-49d5-a965-2b8e13b1d3fb)

I never see the pcd file and there is not the samples folder.
I don't know how to continue it.
Need some help...

**Comment by jackeyEllison** [comment]
![Snipaste_2024-09-20_20-00-06](https://github.com/user-attachments/assets/005a0735-1358-4d2c-8dec-8f71a8809c89)
I also encountered this problem. Does anyone know how to deal with it?
